"""The handoff generator: paired tickets, each an (upstream session, downstream session), where
the downstream session's AREA matches the upstream session's revealed area with probability
`p_match` — and is a random OTHER area otherwise. This is the one genuinely learnable, genuinely
noisy cross-stream signal in the suite: "after upstream finishes on area X, downstream's ticket
is ALSO about X, most of the time."

Reuses workflow.py exactly as-is (compile_model/sample) — a ticket's session is generated by
pinning Config.areas to a SINGLE area, so which area a session is about is fully controlled
rather than left to the model's own uniform area distribution. task_prior is also pinned to one
task (not the point of this test — opener.py already covers task-level bias; this isolates the
CROSS-STREAM area signal cleanly rather than mixing the two).
"""

from __future__ import annotations

import numpy as np

from janus.generators.workflow import Config, compile_model, sample

AREAS = ("auth", "payments", "search", "infra", "ui")
TASK = "bugfix"          # fixed — isolates the test to the area signal, not task-prior bias

_SHARED = dict(alias_rate=0.15, stay=0.2, base_fail=0.05, hard_fail=0.05, flaky_fail=0.05,
              interrupt=0.0)

_MODELS: dict[str, object] = {}


def pinned_model(area: str):
    if area not in _MODELS:
        _MODELS[area] = compile_model(Config(areas=(area,), tasks=(TASK,), **_SHARED))
    return _MODELS[area]


def sample_tickets(n: int, seed: int, p_match: float = 0.85):
    """n tickets: [(upstream_seq, downstream_seq, upstream_area, downstream_area), ...].
    downstream_area == upstream_area with probability p_match, else a uniformly random OTHER
    area — the noisy edge forefetch's confidence gates (min_count, floor) exist to handle."""
    rng = np.random.default_rng(seed)
    tickets = []
    for _ in range(n):
        up_area = rng.choice(AREAS)
        up_seq = sample(pinned_model(up_area), rng)
        if rng.random() < p_match:
            down_area = up_area
        else:
            others = [a for a in AREAS if a != up_area]
            down_area = others[rng.integers(len(others))]
        down_seq = sample(pinned_model(down_area), rng)
        tickets.append((up_seq, down_seq, up_area, down_area))
    return tickets
